languageCode: "en-us"
baseUrl: ""
title: "小鱼驿站"
theme: "anubis"
paginate: 10
disqusShortname: yourdiscussshortname
googleAnalytics: UA-123-45
enableRobotsTXT: true

menu:
  main:
  - identifier: Prometheus
    name: Prometheus
    title: Prometheus
    url: /tags/prometheus
    weight: 1
  - identifier: IPFS
    name: IPFS
    title: IPFS
    url: /tags/ipfs
    weight: 2
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 3
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 4
  - identifier: about
    name: About
    title: About
    url: /about
    weight: 5

params:
  author: "smallfish"
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: false